//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casino.core.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("casino.core.Properties.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tapis.
        /// </summary>
        internal static string AllIn {
            get {
                return ResourceManager.GetString("AllIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As.
        /// </summary>
        internal static string As {
            get {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Miser.
        /// </summary>
        internal static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carte tirée..
        /// </summary>
        internal static string BlackjackCardDrawn {
            get {
                return ResourceManager.GetString("BlackjackCardDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez votre action..
        /// </summary>
        internal static string BlackjackChooseAction {
            get {
                return ResourceManager.GetString("BlackjackChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le croupier.
        /// </summary>
        internal static string BlackjackDealer {
            get {
                return ResourceManager.GetString("BlackjackDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueur.
        /// </summary>
        internal static string BlackjackPlayer {
            get {
                return ResourceManager.GetString("BlackjackPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre tour..
        /// </summary>
        internal static string BlackjackPlayerTurn {
            get {
                return ResourceManager.GetString("BlackjackPlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Égalité.
        /// </summary>
        internal static string BlackjackPushWinner {
            get {
                return ResourceManager.GetString("BlackjackPushWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Push : égalité..
        /// </summary>
        internal static string BlackjackRoundPush {
            get {
                return ResourceManager.GetString("BlackjackRoundPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le croupier remporte cette manche..
        /// </summary>
        internal static string BlackjackRoundWonByDealer {
            get {
                return ResourceManager.GetString("BlackjackRoundWonByDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bravo ! Vous remportez cette manche..
        /// </summary>
        internal static string BlackjackRoundWonByPlayer {
            get {
                return ResourceManager.GetString("BlackjackRoundWonByPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivre.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cinq.
        /// </summary>
        internal static string Cinq {
            get {
                return ResourceManager.GetString("Cinq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dame.
        /// </summary>
        internal static string Dame {
            get {
                return ResourceManager.GetString("Dame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deux.
        /// </summary>
        internal static string Deux {
            get {
                return ResourceManager.GetString("Deux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dix.
        /// </summary>
        internal static string Dix {
            get {
                return ResourceManager.GetString("Dix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune mise supplémentaire à suivre..
        /// </summary>
        internal static string ErrorNoAdditionalBetToCall {
            get {
                return ResourceManager.GetString("ErrorNoAdditionalBetToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le joueur n&apos;a pas assez de jetons pour miser autant..
        /// </summary>
        internal static string ErrorPlayerHasNotEnoughChips {
            get {
                return ResourceManager.GetString("ErrorPlayerHasNotEnoughChips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La mise ne peut pas être inférieure à la mise de départ/actuelle..
        /// </summary>
        internal static string ErrorTheBetAmountCannotBeLowerThanTheInitialBetAmount {
            get {
                return ResourceManager.GetString("ErrorTheBetAmountCannotBeLowerThanTheInitialBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le montant de mise doit être supérieur à zéro..
        /// </summary>
        internal static string ErrorTheBetAmountShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ErrorTheBetAmountShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La mise doit augmenter la contribution du joueur..
        /// </summary>
        internal static string ErrorTheBetShouldIncreaseThePlayerContribution {
            get {
                return ResourceManager.GetString("ErrorTheBetShouldIncreaseThePlayerContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le joueur ne peut pas checker car il y a une mise sur la table..
        /// </summary>
        internal static string ErrorThePlayerCannotCheckBecauseThereIsABetOnTheTable {
            get {
                return ResourceManager.GetString("ErrorThePlayerCannotCheckBecauseThereIsABetOnTheTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le joueur n&apos;a pas assez de jetons pour suivre la mise actuelle..
        /// </summary>
        internal static string ErrorThePlayerDoesNotHaveEnoughChipsToCallTheCurrentBet {
            get {
                return ResourceManager.GetString("ErrorThePlayerDoesNotHaveEnoughChipsToCallTheCurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le joueur n&apos;a pas assez de jetons pour relancer autant..
        /// </summary>
        internal static string ErrorThePlayerDoesNotHaveEnoughChipsToRaiseThatAmount {
            get {
                return ResourceManager.GetString("ErrorThePlayerDoesNotHaveEnoughChipsToRaiseThatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La relance doit être supérieure ou égale à la mise actuelle..
        /// </summary>
        internal static string ErrorTheRaiseMustBeGreaterOrEqualThanTheCurrentBet {
            get {
                return ResourceManager.GetString("ErrorTheRaiseMustBeGreaterOrEqualThanTheCurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleur.
        /// </summary>
        internal static string Flush {
            get {
                return ResourceManager.GetString("Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se Coucher.
        /// </summary>
        internal static string Fold {
            get {
                return ResourceManager.GetString("Fold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carré.
        /// </summary>
        internal static string FourOfAKind {
            get {
                return ResourceManager.GetString("FourOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        internal static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carte Haute.
        /// </summary>
        internal static string HighCard {
            get {
                return ResourceManager.GetString("HighCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Huit.
        /// </summary>
        internal static string Huit {
            get {
                return ResourceManager.GetString("Huit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Neuf.
        /// </summary>
        internal static string Neuf {
            get {
                return ResourceManager.GetString("Neuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paire.
        /// </summary>
        internal static string OnePair {
            get {
                return ResourceManager.GetString("OnePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quatre.
        /// </summary>
        internal static string Quatre {
            get {
                return ResourceManager.GetString("Quatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Relancer.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roi.
        /// </summary>
        internal static string Roi {
            get {
                return ResourceManager.GetString("Roi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quinte Flush Royale.
        /// </summary>
        internal static string RoyalFlush {
            get {
                return ResourceManager.GetString("RoyalFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} de {1}.
        /// </summary>
        internal static string ScoreOfFormat {
            get {
                return ResourceManager.GetString("ScoreOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sept.
        /// </summary>
        internal static string Sept {
            get {
                return ResourceManager.GetString("Sept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Six.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez votre mise puis lancez les rouleaux..
        /// </summary>
        internal static string SlotChooseBet {
            get {
                return ResourceManager.GetString("SlotChooseBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Machine à sous.
        /// </summary>
        internal static string SlotGameName {
            get {
                return ResourceManager.GetString("SlotGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 💥 JACKPOT ! Triple 7 ! Vous gagnez {0} crédits..
        /// </summary>
        internal static string SlotJackpotWin {
            get {
                return ResourceManager.GetString("SlotJackpotWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez plus de crédits. Fin de partie..
        /// </summary>
        internal static string SlotNoCredits {
            get {
                return ResourceManager.GetString("SlotNoCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de gain cette fois. La prochaine sera peut-être la bonne !.
        /// </summary>
        internal static string SlotNoWin {
            get {
                return ResourceManager.GetString("SlotNoWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎰 Les rouleaux tournent... ({0}/{1}).
        /// </summary>
        internal static string SlotReelsSpinning {
            get {
                return ResourceManager.GetString("SlotReelsSpinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎉 Gain de {0} crédits ! Relancez pour tenter mieux..
        /// </summary>
        internal static string SlotRegularWin {
            get {
                return ResourceManager.GetString("SlotRegularWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨ Super combinaison ! Vous gagnez {0} crédits..
        /// </summary>
        internal static string SlotSuperComboWin {
            get {
                return ResourceManager.GetString("SlotSuperComboWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir joué à la machine à sous !.
        /// </summary>
        internal static string SlotThanks {
            get {
                return ResourceManager.GetString("SlotThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue à la machine à sous néon ! Choisissez votre mise..
        /// </summary>
        internal static string SlotWelcome {
            get {
                return ResourceManager.GetString("SlotWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suite.
        /// </summary>
        internal static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quinte Flush.
        /// </summary>
        internal static string StraightFlush {
            get {
                return ResourceManager.GetString("StraightFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brelan.
        /// </summary>
        internal static string ThreeOfAKind {
            get {
                return ResourceManager.GetString("ThreeOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trois.
        /// </summary>
        internal static string Trois {
            get {
                return ResourceManager.GetString("Trois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deux Paires.
        /// </summary>
        internal static string TwoPair {
            get {
                return ResourceManager.GetString("TwoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valet.
        /// </summary>
        internal static string Valet {
            get {
                return ResourceManager.GetString("Valet", resourceCulture);
            }
        }
    }
}
