//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casino.core.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("casino.core.Properties.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ace.
        /// </summary>
        internal static string Ace {
            get {
                return ResourceManager.GetString("Ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AllIn.
        /// </summary>
        internal static string AllIn {
            get {
                return ResourceManager.GetString("AllIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bet.
        /// </summary>
        internal static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Card drawn..
        /// </summary>
        internal static string BlackjackCardDrawn {
            get {
                return ResourceManager.GetString("BlackjackCardDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your action..
        /// </summary>
        internal static string BlackjackChooseAction {
            get {
                return ResourceManager.GetString("BlackjackChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dealer.
        /// </summary>
        internal static string BlackjackDealer {
            get {
                return ResourceManager.GetString("BlackjackDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player.
        /// </summary>
        internal static string BlackjackPlayer {
            get {
                return ResourceManager.GetString("BlackjackPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your turn..
        /// </summary>
        internal static string BlackjackPlayerTurn {
            get {
                return ResourceManager.GetString("BlackjackPlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Push.
        /// </summary>
        internal static string BlackjackPushWinner {
            get {
                return ResourceManager.GetString("BlackjackPushWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Push: tie..
        /// </summary>
        internal static string BlackjackRoundPush {
            get {
                return ResourceManager.GetString("BlackjackRoundPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dealer wins this round..
        /// </summary>
        internal static string BlackjackRoundWonByDealer {
            get {
                return ResourceManager.GetString("BlackjackRoundWonByDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Great! You win this round..
        /// </summary>
        internal static string BlackjackRoundWonByPlayer {
            get {
                return ResourceManager.GetString("BlackjackRoundWonByPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eight.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No additional bet to call..
        /// </summary>
        internal static string ErrorNoAdditionalBetToCall {
            get {
                return ResourceManager.GetString("ErrorNoAdditionalBetToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player has not enough chips..
        /// </summary>
        internal static string ErrorPlayerHasNotEnoughChips {
            get {
                return ResourceManager.GetString("ErrorPlayerHasNotEnoughChips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The bet amount cannot be lower than the initial bet amount..
        /// </summary>
        internal static string ErrorTheBetAmountCannotBeLowerThanTheInitialBetAmount {
            get {
                return ResourceManager.GetString("ErrorTheBetAmountCannotBeLowerThanTheInitialBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The bet amount should be greater than zero..
        /// </summary>
        internal static string ErrorTheBetAmountShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ErrorTheBetAmountShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The bet should increase the player contribution.
        /// </summary>
        internal static string ErrorTheBetShouldIncreaseThePlayerContribution {
            get {
                return ResourceManager.GetString("ErrorTheBetShouldIncreaseThePlayerContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player cannot check because there is a bet on the table..
        /// </summary>
        internal static string ErrorThePlayerCannotCheckBecauseThereIsABetOnTheTable {
            get {
                return ResourceManager.GetString("ErrorThePlayerCannotCheckBecauseThereIsABetOnTheTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player does not have enough chips to call the current bet..
        /// </summary>
        internal static string ErrorThePlayerDoesNotHaveEnoughChipsToCallTheCurrentBet {
            get {
                return ResourceManager.GetString("ErrorThePlayerDoesNotHaveEnoughChipsToCallTheCurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player does not have enough chips to raise that amount..
        /// </summary>
        internal static string ErrorThePlayerDoesNotHaveEnoughChipsToRaiseThatAmount {
            get {
                return ResourceManager.GetString("ErrorThePlayerDoesNotHaveEnoughChipsToRaiseThatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The raise must be greater than or equal to the current bet..
        /// </summary>
        internal static string ErrorTheRaiseMustBeGreaterOrEqualThanTheCurrentBet {
            get {
                return ResourceManager.GetString("ErrorTheRaiseMustBeGreaterOrEqualThanTheCurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Five.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flush.
        /// </summary>
        internal static string Flush {
            get {
                return ResourceManager.GetString("Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fold.
        /// </summary>
        internal static string Fold {
            get {
                return ResourceManager.GetString("Fold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Four.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Four Of A Kind.
        /// </summary>
        internal static string FourOfAKind {
            get {
                return ResourceManager.GetString("FourOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full House.
        /// </summary>
        internal static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High Card.
        /// </summary>
        internal static string HighCard {
            get {
                return ResourceManager.GetString("HighCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jack.
        /// </summary>
        internal static string Jack {
            get {
                return ResourceManager.GetString("Jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à King.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nine.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One Pair.
        /// </summary>
        internal static string OnePair {
            get {
                return ResourceManager.GetString("OnePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queen.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raise.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Black.
        /// </summary>
        internal static string RouletteBetBlack {
            get {
                return ResourceManager.GetString("RouletteBetBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Even.
        /// </summary>
        internal static string RouletteBetEven {
            get {
                return ResourceManager.GetString("RouletteBetEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Odd.
        /// </summary>
        internal static string RouletteBetOdd {
            get {
                return ResourceManager.GetString("RouletteBetOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red.
        /// </summary>
        internal static string RouletteBetRed {
            get {
                return ResourceManager.GetString("RouletteBetRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Straight {0}.
        /// </summary>
        internal static string RouletteBetStraightNumber {
            get {
                return ResourceManager.GetString("RouletteBetStraightNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Place your bet for the next spin..
        /// </summary>
        internal static string RouletteChooseBet {
            get {
                return ResourceManager.GetString("RouletteChooseBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à black.
        /// </summary>
        internal static string RouletteColorBlack {
            get {
                return ResourceManager.GetString("RouletteColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à red.
        /// </summary>
        internal static string RouletteColorRed {
            get {
                return ResourceManager.GetString("RouletteColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roulette.
        /// </summary>
        internal static string RouletteGameName {
            get {
                return ResourceManager.GetString("RouletteGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. No win on this spin..
        /// </summary>
        internal static string RouletteLose {
            get {
                return ResourceManager.GetString("RouletteLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are out of roulette credits..
        /// </summary>
        internal static string RouletteNoCredits {
            get {
                return ResourceManager.GetString("RouletteNoCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1}.
        /// </summary>
        internal static string RoulettePocketColored {
            get {
                return ResourceManager.GetString("RoulettePocketColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} green.
        /// </summary>
        internal static string RoulettePocketGreen {
            get {
                return ResourceManager.GetString("RoulettePocketGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for playing roulette..
        /// </summary>
        internal static string RouletteThanks {
            get {
                return ResourceManager.GetString("RouletteThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to European roulette. Place your bet..
        /// </summary>
        internal static string RouletteWelcome {
            get {
                return ResourceManager.GetString("RouletteWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wheel spinning... ({0}/{1}).
        /// </summary>
        internal static string RouletteWheelSpinning {
            get {
                return ResourceManager.GetString("RouletteWheelSpinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}! Your outside bet wins {1} credits..
        /// </summary>
        internal static string RouletteWinColor {
            get {
                return ResourceManager.GetString("RouletteWinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}! Straight-up hit, you win {1} credits..
        /// </summary>
        internal static string RouletteWinNumber {
            get {
                return ResourceManager.GetString("RouletteWinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}! Your parity bet wins {1} credits..
        /// </summary>
        internal static string RouletteWinParity {
            get {
                return ResourceManager.GetString("RouletteWinParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Royal Flush.
        /// </summary>
        internal static string RoyalFlush {
            get {
                return ResourceManager.GetString("RoyalFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} of {1}.
        /// </summary>
        internal static string ScoreOfFormat {
            get {
                return ResourceManager.GetString("ScoreOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seven.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Six.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your bet then spin the reels..
        /// </summary>
        internal static string SlotChooseBet {
            get {
                return ResourceManager.GetString("SlotChooseBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slot Machine.
        /// </summary>
        internal static string SlotGameName {
            get {
                return ResourceManager.GetString("SlotGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 💥 JACKPOT! Triple 7! You win {0} credits..
        /// </summary>
        internal static string SlotJackpotWin {
            get {
                return ResourceManager.GetString("SlotJackpotWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have no credits left. Game over..
        /// </summary>
        internal static string SlotNoCredits {
            get {
                return ResourceManager.GetString("SlotNoCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No win this time. Maybe next spin!.
        /// </summary>
        internal static string SlotNoWin {
            get {
                return ResourceManager.GetString("SlotNoWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎰 Reels spinning... ({0}/{1}).
        /// </summary>
        internal static string SlotReelsSpinning {
            get {
                return ResourceManager.GetString("SlotReelsSpinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎉 You win {0} credits! Spin again to try for better..
        /// </summary>
        internal static string SlotRegularWin {
            get {
                return ResourceManager.GetString("SlotRegularWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨ Super combo! You win {0} credits..
        /// </summary>
        internal static string SlotSuperComboWin {
            get {
                return ResourceManager.GetString("SlotSuperComboWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for playing the slot machine!.
        /// </summary>
        internal static string SlotThanks {
            get {
                return ResourceManager.GetString("SlotThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the neon slot machine! Choose your bet..
        /// </summary>
        internal static string SlotWelcome {
            get {
                return ResourceManager.GetString("SlotWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Straight.
        /// </summary>
        internal static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Straight Flush.
        /// </summary>
        internal static string StraightFlush {
            get {
                return ResourceManager.GetString("StraightFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ten.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Three.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Three Of A Kind.
        /// </summary>
        internal static string ThreeOfAKind {
            get {
                return ResourceManager.GetString("ThreeOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two Pair.
        /// </summary>
        internal static string TwoPair {
            get {
                return ResourceManager.GetString("TwoPair", resourceCulture);
            }
        }
    }
}
