//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casino.core.Properties.Langages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("casino.core.Properties.Langages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AllIn.
        /// </summary>
        internal static string AllIn {
            get {
                return ResourceManager.GetString("AllIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bet.
        /// </summary>
        internal static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No additional bet to call..
        /// </summary>
        internal static string ErrorNoAdditionalBetToCall {
            get {
                return ResourceManager.GetString("ErrorNoAdditionalBetToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player has not enough chips..
        /// </summary>
        internal static string ErrorPlayerHasNotEnoughChips {
            get {
                return ResourceManager.GetString("ErrorPlayerHasNotEnoughChips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The bet amount cannot be lower than the initial bet amount..
        /// </summary>
        internal static string ErrorTheBetAmountCannotBeLowerThanTheInitialBetAmount {
            get {
                return ResourceManager.GetString("ErrorTheBetAmountCannotBeLowerThanTheInitialBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The bet amount should be greater than zero..
        /// </summary>
        internal static string ErrorTheBetAmountShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ErrorTheBetAmountShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The bet should increase the player contribution.
        /// </summary>
        internal static string ErrorTheBetShouldIncreaseThePlayerContribution {
            get {
                return ResourceManager.GetString("ErrorTheBetShouldIncreaseThePlayerContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player cannot check because there is a bet on the table..
        /// </summary>
        internal static string ErrorThePlayerCannotCheckBecauseThereIsABetOnTheTable {
            get {
                return ResourceManager.GetString("ErrorThePlayerCannotCheckBecauseThereIsABetOnTheTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player does not have enough chips to call the current bet..
        /// </summary>
        internal static string ErrorThePlayerDoesNotHaveEnoughChipsToCallTheCurrentBet {
            get {
                return ResourceManager.GetString("ErrorThePlayerDoesNotHaveEnoughChipsToCallTheCurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The player does not have enough chips to raise that amount..
        /// </summary>
        internal static string ErrorThePlayerDoesNotHaveEnoughChipsToRaiseThatAmount {
            get {
                return ResourceManager.GetString("ErrorThePlayerDoesNotHaveEnoughChipsToRaiseThatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The raise must be greater than or equal to the current bet..
        /// </summary>
        internal static string ErrorTheRaiseMustBeGreaterOrEqualThanTheCurrentBet {
            get {
                return ResourceManager.GetString("ErrorTheRaiseMustBeGreaterOrEqualThanTheCurrentBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flush.
        /// </summary>
        internal static string Flush {
            get {
                return ResourceManager.GetString("Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fold.
        /// </summary>
        internal static string Fold {
            get {
                return ResourceManager.GetString("Fold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Four Of A Kind.
        /// </summary>
        internal static string FourOfAKind {
            get {
                return ResourceManager.GetString("FourOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full House.
        /// </summary>
        internal static string FullHouse {
            get {
                return ResourceManager.GetString("FullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High Card.
        /// </summary>
        internal static string HighCard {
            get {
                return ResourceManager.GetString("HighCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One Pair.
        /// </summary>
        internal static string OnePair {
            get {
                return ResourceManager.GetString("OnePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raise.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Royal Flush.
        /// </summary>
        internal static string RoyalFlush {
            get {
                return ResourceManager.GetString("RoyalFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Straight.
        /// </summary>
        internal static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Straight Flush.
        /// </summary>
        internal static string StraightFlush {
            get {
                return ResourceManager.GetString("StraightFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Three Of A Kind.
        /// </summary>
        internal static string ThreeOfAKind {
            get {
                return ResourceManager.GetString("ThreeOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two Pair.
        /// </summary>
        internal static string TwoPair {
            get {
                return ResourceManager.GetString("TwoPair", resourceCulture);
            }
        }
    }
}
